spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8888
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method