spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  cloud.stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        employee-channel:
          destination: employee-topic

server:
  port: 8888

